spring:
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: shortner_url
    schema-action: create_if_not_exists
    local-datacenter: dc1

  data:
    redis:
      port: 6379
      host: localhost
redis:
  key-counter: my_counter
  init-counter: 14000000